#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2018.3 (64-bit)
#
# Filename    : Fast_IP_Clock.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Tue Feb 26 11:26:58 -0800 2019
# SW Build 2405991 on Thu Dec  6 23:38:27 MST 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved. 
#
# usage: Fast_IP_Clock.sh [-help]
# usage: Fast_IP_Clock.sh [-lib_map_path]
# usage: Fast_IP_Clock.sh [-noclean_files]
# usage: Fast_IP_Clock.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'Fast_IP_Clock.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xil_defaultlib xpm axi_lite_ipif_v3_0_4 mdm_v3_2_15 lib_cdc_v1_0_2 interrupt_control_v3_1_4 axi_gpio_v2_0_20 microblaze_v11_0_0 lmb_v10_v3_0_9 lmb_bram_if_cntlr_v4_0_15 blk_mem_gen_v8_4_2 proc_sys_reset_v5_0_13 axi_intc_v4_1_12 xlconcat_v2_1_1 generic_baseblocks_v2_1_0 axi_infrastructure_v1_1_0 axi_register_slice_v2_1_18 fifo_generator_v13_2_3 axi_data_fifo_v2_1_17 axi_crossbar_v2_1_19 lib_pkg_v1_0_2 lib_srl_fifo_v1_0_2 axi_uart16550_v2_0_20 lib_bmg_v1_0_11 lib_fifo_v1_0_12 axi_ethernetlite_v3_0_16 mii_to_rmii_v2_0_20 axi_timer_v2_0_20 axi_clock_converter_v2_1_17 axi_protocol_converter_v2_1_18)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "Fast_IP_Clock.sh - Script generated by export_simulation (Vivado v2018.3 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/85a3" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/ec67/hdl" \
    "D:/Xilinx/Vivado/2018.3/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "D:/Xilinx/Vivado/2018.3/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "D:/Xilinx/Vivado/2018.3/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "D:/Xilinx/Vivado/2018.3/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work mdm_v3_2_15 $vhdlan_opts \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/41ef/hdl/mdm_v3_2_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/Fast_IP_Clock/ip/Fast_IP_Clock_mdm_1_0/sim/Fast_IP_Clock_mdm_1_0.vhd" \
    "$ref_dir/../../../bd/Fast_IP_Clock/ipshared/5085/hdl/psram_ip_v1_0_S00_AXI.vhd" \
    "$ref_dir/../../../bd/Fast_IP_Clock/ipshared/5085/hdl/psram_ip_v1_0.vhd" \
    "$ref_dir/../../../bd/Fast_IP_Clock/ipshared/5085/hdl/AsyncPSRAM.vhd" \
    "$ref_dir/../../../bd/Fast_IP_Clock/ip/Fast_IP_Clock_psram_ip_0_0/sim/Fast_IP_Clock_psram_ip_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work interrupt_control_v3_1_4 $vhdlan_opts \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/a040/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_gpio_v2_0_20 $vhdlan_opts \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/a7c9/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/Fast_IP_Clock/ip/Fast_IP_Clock_axi_gpio_0_0/sim/Fast_IP_Clock_axi_gpio_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/85a3" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/ec67/hdl" \
    "$ref_dir/../../../bd/Fast_IP_Clock/ip/Fast_IP_Clock_clk_wiz_0_0/Fast_IP_Clock_clk_wiz_0_0_clk_wiz.v" \
    "$ref_dir/../../../bd/Fast_IP_Clock/ip/Fast_IP_Clock_clk_wiz_0_0/Fast_IP_Clock_clk_wiz_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work microblaze_v11_0_0 $vhdlan_opts \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/2ed1/hdl/microblaze_v11_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/Fast_IP_Clock/ip/Fast_IP_Clock_microblaze_0_0/sim/Fast_IP_Clock_microblaze_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lmb_v10_v3_0_9 $vhdlan_opts \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/78eb/hdl/lmb_v10_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/Fast_IP_Clock/ip/Fast_IP_Clock_dlmb_v10_0/sim/Fast_IP_Clock_dlmb_v10_0.vhd" \
    "$ref_dir/../../../bd/Fast_IP_Clock/ip/Fast_IP_Clock_ilmb_v10_0/sim/Fast_IP_Clock_ilmb_v10_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lmb_bram_if_cntlr_v4_0_15 $vhdlan_opts \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/92fd/hdl/lmb_bram_if_cntlr_v4_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/Fast_IP_Clock/ip/Fast_IP_Clock_dlmb_bram_if_cntlr_0/sim/Fast_IP_Clock_dlmb_bram_if_cntlr_0.vhd" \
    "$ref_dir/../../../bd/Fast_IP_Clock/ip/Fast_IP_Clock_ilmb_bram_if_cntlr_0/sim/Fast_IP_Clock_ilmb_bram_if_cntlr_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work blk_mem_gen_v8_4_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/85a3" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/ec67/hdl" \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/37c2/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/85a3" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/ec67/hdl" \
    "$ref_dir/../../../bd/Fast_IP_Clock/ip/Fast_IP_Clock_lmb_bram_0/sim/Fast_IP_Clock_lmb_bram_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/Fast_IP_Clock/ip/Fast_IP_Clock_proc_sys_reset_0_0/sim/Fast_IP_Clock_proc_sys_reset_0_0.vhd" \
    "$ref_dir/../../../bd/Fast_IP_Clock/ip/Fast_IP_Clock_proc_sys_reset_1_0/sim/Fast_IP_Clock_proc_sys_reset_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_intc_v4_1_12 $vhdlan_opts \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/31e4/hdl/axi_intc_v4_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/Fast_IP_Clock/ip/Fast_IP_Clock_axi_intc_0_0/sim/Fast_IP_Clock_axi_intc_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlconcat_v2_1_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/85a3" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/ec67/hdl" \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/2f66/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/85a3" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/ec67/hdl" \
    "$ref_dir/../../../bd/Fast_IP_Clock/ip/Fast_IP_Clock_xlconcat_0_0/sim/Fast_IP_Clock_xlconcat_0_0.v" \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/cdef/hdl/verilog/calc_buf_r_m_axi.v" \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/cdef/hdl/verilog/calc_in_parms_s_axi.v" \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/cdef/hdl/verilog/calc_mem_0.v" \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/cdef/hdl/verilog/calc_mul_12ns_40sfYi.v" \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/cdef/hdl/verilog/calc_mul_40s_40s_bkb.v" \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/cdef/hdl/verilog/calc_mul_40s_41s_dEe.v" \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/cdef/hdl/verilog/calc_mul_41s_40s_cud.v" \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/cdef/hdl/verilog/calc_mux_432_16_1_1.v" \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/cdef/hdl/verilog/calc_sdiv_41ns_13eOg.v" \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/cdef/hdl/verilog/mandel_calc.v" \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/cdef/hdl/verilog/pretest.v" \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/cdef/hdl/verilog/calc.v" \
    "$ref_dir/../../../bd/Fast_IP_Clock/ip/Fast_IP_Clock_calc_0_0/sim/Fast_IP_Clock_calc_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/85a3" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/ec67/hdl" \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/85a3" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/ec67/hdl" \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_18 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/85a3" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/ec67/hdl" \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/cc23/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_2_3 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/85a3" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/ec67/hdl" \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/64f4/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_3 $vhdlan_opts \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/64f4/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_3 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/85a3" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/ec67/hdl" \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/64f4/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_17 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/85a3" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/ec67/hdl" \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/c4fd/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_19 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/85a3" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/ec67/hdl" \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/6c9d/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/85a3" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/ec67/hdl" \
    "$ref_dir/../../../bd/Fast_IP_Clock/ip/Fast_IP_Clock_xbar_1/sim/Fast_IP_Clock_xbar_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_uart16550_v2_0_20 $vhdlan_opts \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/07cf/hdl/axi_uart16550_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/Fast_IP_Clock/ip/Fast_IP_Clock_axi_uart16550_0_0/sim/Fast_IP_Clock_axi_uart16550_0_0.vhd" \
    "$ref_dir/../../../bd/Fast_IP_Clock/ip/Fast_IP_Clock_proc_sys_reset_2_0/sim/Fast_IP_Clock_proc_sys_reset_2_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/85a3" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/ec67/hdl" \
    "$ref_dir/../../../bd/Fast_IP_Clock/sim/Fast_IP_Clock.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_bmg_v1_0_11 $vhdlan_opts \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/556c/hdl/lib_bmg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_fifo_v1_0_12 $vhdlan_opts \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/544a/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_ethernetlite_v3_0_16 $vhdlan_opts \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/5576/hdl/axi_ethernetlite_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/Fast_IP_Clock/ip/Fast_IP_Clock_axi_ethernetlite_0_0/sim/Fast_IP_Clock_axi_ethernetlite_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work mii_to_rmii_v2_0_20 $vhdlan_opts \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/90e9/hdl/mii_to_rmii_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/Fast_IP_Clock/ip/Fast_IP_Clock_mii_to_rmii_0_0/sim/Fast_IP_Clock_mii_to_rmii_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_timer_v2_0_20 $vhdlan_opts \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/e9c1/hdl/axi_timer_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/Fast_IP_Clock/ip/Fast_IP_Clock_axi_timer_0_0/sim/Fast_IP_Clock_axi_timer_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_clock_converter_v2_1_17 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/85a3" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/ec67/hdl" \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/693a/hdl/axi_clock_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/85a3" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/ec67/hdl" \
    "$ref_dir/../../../bd/Fast_IP_Clock/ip/Fast_IP_Clock_auto_cc_2/sim/Fast_IP_Clock_auto_cc_2.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_18 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/85a3" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/ec67/hdl" \
    "$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/7a04/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/85a3" +incdir+"$ref_dir/../../../../project_1.srcs/sources_1/bd/Fast_IP_Clock/ipshared/ec67/hdl" \
    "$ref_dir/../../../bd/Fast_IP_Clock/ip/Fast_IP_Clock_auto_pc_7/sim/Fast_IP_Clock_auto_pc_7.v" \
    "$ref_dir/../../../bd/Fast_IP_Clock/ip/Fast_IP_Clock_auto_cc_3/sim/Fast_IP_Clock_auto_cc_3.v" \
    "$ref_dir/../../../bd/Fast_IP_Clock/ip/Fast_IP_Clock_auto_cc_4/sim/Fast_IP_Clock_auto_cc_4.v" \
    "$ref_dir/../../../bd/Fast_IP_Clock/ip/Fast_IP_Clock_auto_pc_0/sim/Fast_IP_Clock_auto_pc_0.v" \
    "$ref_dir/../../../bd/Fast_IP_Clock/ip/Fast_IP_Clock_auto_pc_1/sim/Fast_IP_Clock_auto_pc_1.v" \
    "$ref_dir/../../../bd/Fast_IP_Clock/ip/Fast_IP_Clock_auto_pc_2/sim/Fast_IP_Clock_auto_pc_2.v" \
    "$ref_dir/../../../bd/Fast_IP_Clock/ip/Fast_IP_Clock_auto_cc_0/sim/Fast_IP_Clock_auto_cc_0.v" \
    "$ref_dir/../../../bd/Fast_IP_Clock/ip/Fast_IP_Clock_auto_pc_3/sim/Fast_IP_Clock_auto_pc_3.v" \
    "$ref_dir/../../../bd/Fast_IP_Clock/ip/Fast_IP_Clock_auto_cc_1/sim/Fast_IP_Clock_auto_cc_1.v" \
    "$ref_dir/../../../bd/Fast_IP_Clock/ip/Fast_IP_Clock_auto_pc_4/sim/Fast_IP_Clock_auto_pc_4.v" \
    "$ref_dir/../../../bd/Fast_IP_Clock/ip/Fast_IP_Clock_auto_pc_5/sim/Fast_IP_Clock_auto_pc_5.v" \
    "$ref_dir/../../../bd/Fast_IP_Clock/ip/Fast_IP_Clock_auto_pc_6/sim/Fast_IP_Clock_auto_pc_6.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.Fast_IP_Clock xil_defaultlib.glbl -o Fast_IP_Clock_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./Fast_IP_Clock_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./Fast_IP_Clock.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key Fast_IP_Clock_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc Fast_IP_Clock_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./Fast_IP_Clock.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: Fast_IP_Clock.sh [-help]\n\
Usage: Fast_IP_Clock.sh [-lib_map_path]\n\
Usage: Fast_IP_Clock.sh [-reset_run]\n\
Usage: Fast_IP_Clock.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
