// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="calc,hls_ip_2018_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7a100tcsg324-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.750000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=6,HLS_SYN_DSP=148,HLS_SYN_FF=12172,HLS_SYN_LUT=16025,HLS_VERSION=2018_3}" *)

module calc (
        ap_clk,
        ap_rst_n,
        m_axi_buf_r_AWVALID,
        m_axi_buf_r_AWREADY,
        m_axi_buf_r_AWADDR,
        m_axi_buf_r_AWID,
        m_axi_buf_r_AWLEN,
        m_axi_buf_r_AWSIZE,
        m_axi_buf_r_AWBURST,
        m_axi_buf_r_AWLOCK,
        m_axi_buf_r_AWCACHE,
        m_axi_buf_r_AWPROT,
        m_axi_buf_r_AWQOS,
        m_axi_buf_r_AWREGION,
        m_axi_buf_r_AWUSER,
        m_axi_buf_r_WVALID,
        m_axi_buf_r_WREADY,
        m_axi_buf_r_WDATA,
        m_axi_buf_r_WSTRB,
        m_axi_buf_r_WLAST,
        m_axi_buf_r_WID,
        m_axi_buf_r_WUSER,
        m_axi_buf_r_ARVALID,
        m_axi_buf_r_ARREADY,
        m_axi_buf_r_ARADDR,
        m_axi_buf_r_ARID,
        m_axi_buf_r_ARLEN,
        m_axi_buf_r_ARSIZE,
        m_axi_buf_r_ARBURST,
        m_axi_buf_r_ARLOCK,
        m_axi_buf_r_ARCACHE,
        m_axi_buf_r_ARPROT,
        m_axi_buf_r_ARQOS,
        m_axi_buf_r_ARREGION,
        m_axi_buf_r_ARUSER,
        m_axi_buf_r_RVALID,
        m_axi_buf_r_RREADY,
        m_axi_buf_r_RDATA,
        m_axi_buf_r_RLAST,
        m_axi_buf_r_RID,
        m_axi_buf_r_RUSER,
        m_axi_buf_r_RRESP,
        m_axi_buf_r_BVALID,
        m_axi_buf_r_BREADY,
        m_axi_buf_r_BRESP,
        m_axi_buf_r_BID,
        m_axi_buf_r_BUSER,
        s_axi_in_parms_AWVALID,
        s_axi_in_parms_AWREADY,
        s_axi_in_parms_AWADDR,
        s_axi_in_parms_WVALID,
        s_axi_in_parms_WREADY,
        s_axi_in_parms_WDATA,
        s_axi_in_parms_WSTRB,
        s_axi_in_parms_ARVALID,
        s_axi_in_parms_ARREADY,
        s_axi_in_parms_ARADDR,
        s_axi_in_parms_RVALID,
        s_axi_in_parms_RREADY,
        s_axi_in_parms_RDATA,
        s_axi_in_parms_RRESP,
        s_axi_in_parms_BVALID,
        s_axi_in_parms_BREADY,
        s_axi_in_parms_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 52'd1;
parameter    ap_ST_fsm_state2 = 52'd2;
parameter    ap_ST_fsm_state3 = 52'd4;
parameter    ap_ST_fsm_state4 = 52'd8;
parameter    ap_ST_fsm_state5 = 52'd16;
parameter    ap_ST_fsm_state6 = 52'd32;
parameter    ap_ST_fsm_state7 = 52'd64;
parameter    ap_ST_fsm_state8 = 52'd128;
parameter    ap_ST_fsm_state9 = 52'd256;
parameter    ap_ST_fsm_state10 = 52'd512;
parameter    ap_ST_fsm_state11 = 52'd1024;
parameter    ap_ST_fsm_state12 = 52'd2048;
parameter    ap_ST_fsm_state13 = 52'd4096;
parameter    ap_ST_fsm_state14 = 52'd8192;
parameter    ap_ST_fsm_state15 = 52'd16384;
parameter    ap_ST_fsm_state16 = 52'd32768;
parameter    ap_ST_fsm_state17 = 52'd65536;
parameter    ap_ST_fsm_state18 = 52'd131072;
parameter    ap_ST_fsm_state19 = 52'd262144;
parameter    ap_ST_fsm_state20 = 52'd524288;
parameter    ap_ST_fsm_state21 = 52'd1048576;
parameter    ap_ST_fsm_state22 = 52'd2097152;
parameter    ap_ST_fsm_state23 = 52'd4194304;
parameter    ap_ST_fsm_state24 = 52'd8388608;
parameter    ap_ST_fsm_state25 = 52'd16777216;
parameter    ap_ST_fsm_state26 = 52'd33554432;
parameter    ap_ST_fsm_state27 = 52'd67108864;
parameter    ap_ST_fsm_state28 = 52'd134217728;
parameter    ap_ST_fsm_state29 = 52'd268435456;
parameter    ap_ST_fsm_state30 = 52'd536870912;
parameter    ap_ST_fsm_state31 = 52'd1073741824;
parameter    ap_ST_fsm_state32 = 52'd2147483648;
parameter    ap_ST_fsm_state33 = 52'd4294967296;
parameter    ap_ST_fsm_state34 = 52'd8589934592;
parameter    ap_ST_fsm_state35 = 52'd17179869184;
parameter    ap_ST_fsm_state36 = 52'd34359738368;
parameter    ap_ST_fsm_state37 = 52'd68719476736;
parameter    ap_ST_fsm_state38 = 52'd137438953472;
parameter    ap_ST_fsm_state39 = 52'd274877906944;
parameter    ap_ST_fsm_state40 = 52'd549755813888;
parameter    ap_ST_fsm_state41 = 52'd1099511627776;
parameter    ap_ST_fsm_state42 = 52'd2199023255552;
parameter    ap_ST_fsm_state43 = 52'd4398046511104;
parameter    ap_ST_fsm_state44 = 52'd8796093022208;
parameter    ap_ST_fsm_state45 = 52'd17592186044416;
parameter    ap_ST_fsm_state46 = 52'd35184372088832;
parameter    ap_ST_fsm_state47 = 52'd70368744177664;
parameter    ap_ST_fsm_state48 = 52'd140737488355328;
parameter    ap_ST_fsm_state49 = 52'd281474976710656;
parameter    ap_ST_fsm_state50 = 52'd562949953421312;
parameter    ap_ST_fsm_pp0_stage0 = 52'd1125899906842624;
parameter    ap_ST_fsm_state59 = 52'd2251799813685248;
parameter    C_S_AXI_IN_PARMS_DATA_WIDTH = 32;
parameter    C_S_AXI_IN_PARMS_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_BUF_R_ID_WIDTH = 1;
parameter    C_M_AXI_BUF_R_ADDR_WIDTH = 32;
parameter    C_M_AXI_BUF_R_DATA_WIDTH = 32;
parameter    C_M_AXI_BUF_R_AWUSER_WIDTH = 1;
parameter    C_M_AXI_BUF_R_ARUSER_WIDTH = 1;
parameter    C_M_AXI_BUF_R_WUSER_WIDTH = 1;
parameter    C_M_AXI_BUF_R_RUSER_WIDTH = 1;
parameter    C_M_AXI_BUF_R_BUSER_WIDTH = 1;
parameter    C_M_AXI_BUF_R_TARGET_ADDR = 0;
parameter    C_M_AXI_BUF_R_USER_VALUE = 0;
parameter    C_M_AXI_BUF_R_PROT_VALUE = 0;
parameter    C_M_AXI_BUF_R_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_IN_PARMS_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_BUF_R_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_buf_r_AWVALID;
input   m_axi_buf_r_AWREADY;
output  [C_M_AXI_BUF_R_ADDR_WIDTH - 1:0] m_axi_buf_r_AWADDR;
output  [C_M_AXI_BUF_R_ID_WIDTH - 1:0] m_axi_buf_r_AWID;
output  [7:0] m_axi_buf_r_AWLEN;
output  [2:0] m_axi_buf_r_AWSIZE;
output  [1:0] m_axi_buf_r_AWBURST;
output  [1:0] m_axi_buf_r_AWLOCK;
output  [3:0] m_axi_buf_r_AWCACHE;
output  [2:0] m_axi_buf_r_AWPROT;
output  [3:0] m_axi_buf_r_AWQOS;
output  [3:0] m_axi_buf_r_AWREGION;
output  [C_M_AXI_BUF_R_AWUSER_WIDTH - 1:0] m_axi_buf_r_AWUSER;
output   m_axi_buf_r_WVALID;
input   m_axi_buf_r_WREADY;
output  [C_M_AXI_BUF_R_DATA_WIDTH - 1:0] m_axi_buf_r_WDATA;
output  [C_M_AXI_BUF_R_WSTRB_WIDTH - 1:0] m_axi_buf_r_WSTRB;
output   m_axi_buf_r_WLAST;
output  [C_M_AXI_BUF_R_ID_WIDTH - 1:0] m_axi_buf_r_WID;
output  [C_M_AXI_BUF_R_WUSER_WIDTH - 1:0] m_axi_buf_r_WUSER;
output   m_axi_buf_r_ARVALID;
input   m_axi_buf_r_ARREADY;
output  [C_M_AXI_BUF_R_ADDR_WIDTH - 1:0] m_axi_buf_r_ARADDR;
output  [C_M_AXI_BUF_R_ID_WIDTH - 1:0] m_axi_buf_r_ARID;
output  [7:0] m_axi_buf_r_ARLEN;
output  [2:0] m_axi_buf_r_ARSIZE;
output  [1:0] m_axi_buf_r_ARBURST;
output  [1:0] m_axi_buf_r_ARLOCK;
output  [3:0] m_axi_buf_r_ARCACHE;
output  [2:0] m_axi_buf_r_ARPROT;
output  [3:0] m_axi_buf_r_ARQOS;
output  [3:0] m_axi_buf_r_ARREGION;
output  [C_M_AXI_BUF_R_ARUSER_WIDTH - 1:0] m_axi_buf_r_ARUSER;
input   m_axi_buf_r_RVALID;
output   m_axi_buf_r_RREADY;
input  [C_M_AXI_BUF_R_DATA_WIDTH - 1:0] m_axi_buf_r_RDATA;
input   m_axi_buf_r_RLAST;
input  [C_M_AXI_BUF_R_ID_WIDTH - 1:0] m_axi_buf_r_RID;
input  [C_M_AXI_BUF_R_RUSER_WIDTH - 1:0] m_axi_buf_r_RUSER;
input  [1:0] m_axi_buf_r_RRESP;
input   m_axi_buf_r_BVALID;
output   m_axi_buf_r_BREADY;
input  [1:0] m_axi_buf_r_BRESP;
input  [C_M_AXI_BUF_R_ID_WIDTH - 1:0] m_axi_buf_r_BID;
input  [C_M_AXI_BUF_R_BUSER_WIDTH - 1:0] m_axi_buf_r_BUSER;
input   s_axi_in_parms_AWVALID;
output   s_axi_in_parms_AWREADY;
input  [C_S_AXI_IN_PARMS_ADDR_WIDTH - 1:0] s_axi_in_parms_AWADDR;
input   s_axi_in_parms_WVALID;
output   s_axi_in_parms_WREADY;
input  [C_S_AXI_IN_PARMS_DATA_WIDTH - 1:0] s_axi_in_parms_WDATA;
input  [C_S_AXI_IN_PARMS_WSTRB_WIDTH - 1:0] s_axi_in_parms_WSTRB;
input   s_axi_in_parms_ARVALID;
output   s_axi_in_parms_ARREADY;
input  [C_S_AXI_IN_PARMS_ADDR_WIDTH - 1:0] s_axi_in_parms_ARADDR;
output   s_axi_in_parms_RVALID;
input   s_axi_in_parms_RREADY;
output  [C_S_AXI_IN_PARMS_DATA_WIDTH - 1:0] s_axi_in_parms_RDATA;
output  [1:0] s_axi_in_parms_RRESP;
output   s_axi_in_parms_BVALID;
input   s_axi_in_parms_BREADY;
output  [1:0] s_axi_in_parms_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [51:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [39:0] X0_V;
wire   [39:0] Y0_V;
wire   [39:0] X1_V;
wire   [11:0] width_V;
reg    buf_r_blk_n_AW;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] exitcond2_reg_1440;
reg    buf_r_blk_n_W;
reg    ap_enable_reg_pp0_iter2;
reg   [0:0] exitcond2_reg_1440_pp0_iter1_reg;
reg    buf_r_blk_n_B;
reg    ap_enable_reg_pp0_iter7;
reg   [0:0] exitcond2_reg_1440_pp0_iter6_reg;
reg    buf_r_AWVALID;
wire    buf_r_AWREADY;
reg    buf_r_WVALID;
wire    buf_r_WREADY;
wire    buf_r_ARREADY;
wire    buf_r_RVALID;
wire   [15:0] buf_r_RDATA;
wire    buf_r_RLAST;
wire   [0:0] buf_r_RID;
wire   [0:0] buf_r_RUSER;
wire   [1:0] buf_r_RRESP;
wire    buf_r_BVALID;
reg    buf_r_BREADY;
wire   [1:0] buf_r_BRESP;
wire   [0:0] buf_r_BID;
wire   [0:0] buf_r_BUSER;
reg   [23:0] index_1_reg_316;
reg   [11:0] i_op_assign_reg_326;
reg   [11:0] width_V_read_reg_1288;
reg   [39:0] Y0_V_read_reg_1296;
reg  signed [39:0] X0_V_read_reg_1301;
reg   [11:0] height_V_reg_1320;
wire    ap_CS_fsm_state45;
wire   [23:0] tmp_2_cast_fu_493_p1;
reg   [23:0] tmp_2_cast_reg_1325;
wire  signed [51:0] tmp_31_fu_496_p1;
reg  signed [51:0] tmp_31_reg_1332;
wire  signed [51:0] lhs_V_8_cast_fu_500_p1;
reg  signed [51:0] lhs_V_8_cast_reg_1340;
wire  signed [40:0] rhs_V_4_fu_503_p1;
reg  signed [40:0] rhs_V_4_reg_1348;
wire   [11:0] line_V_fu_512_p2;
reg   [11:0] line_V_reg_1356;
wire    ap_CS_fsm_state46;
wire   [0:0] exitcond3_fu_518_p2;
wire    ap_CS_fsm_state47;
wire   [51:0] r_V_s_fu_527_p2;
reg   [51:0] r_V_s_reg_1365;
wire   [39:0] tmp_68_fu_532_p1;
reg   [39:0] tmp_68_reg_1370;
reg   [9:0] newIndex2_reg_1375;
wire   [51:0] r_V_23_1_fu_556_p2;
reg   [51:0] r_V_23_1_reg_1380;
wire   [39:0] tmp_71_fu_561_p1;
reg   [39:0] tmp_71_reg_1385;
wire   [51:0] r_V_23_2_fu_575_p2;
reg   [51:0] r_V_23_2_reg_1390;
wire   [39:0] tmp_74_fu_580_p1;
reg   [39:0] tmp_74_reg_1395;
wire   [51:0] r_V_23_3_fu_594_p2;
reg   [51:0] r_V_23_3_reg_1400;
wire   [39:0] tmp_77_fu_599_p1;
reg   [39:0] tmp_77_reg_1405;
wire   [11:0] pix_x_V_3_fu_603_p2;
reg   [11:0] pix_x_V_3_reg_1410;
wire   [23:0] index_3_fu_609_p2;
reg   [23:0] index_3_reg_1415;
wire   [39:0] p_0_fu_730_p3;
reg   [39:0] p_0_reg_1420;
wire    ap_CS_fsm_state48;
wire   [39:0] p_0_1_fu_854_p3;
reg   [39:0] p_0_1_reg_1425;
wire   [39:0] p_0_2_fu_978_p3;
reg   [39:0] p_0_2_reg_1430;
wire   [39:0] p_0_3_fu_1102_p3;
reg   [39:0] p_0_3_reg_1435;
wire   [0:0] exitcond2_fu_1117_p2;
wire    ap_block_state51_pp0_stage0_iter0;
wire    ap_block_state52_pp0_stage0_iter1;
reg    ap_sig_ioackin_buf_r_AWREADY;
reg    ap_block_state52_io;
wire    ap_block_state53_pp0_stage0_iter2;
reg    ap_sig_ioackin_buf_r_WREADY;
reg    ap_block_state53_io;
wire    ap_block_state54_pp0_stage0_iter3;
wire    ap_block_state55_pp0_stage0_iter4;
wire    ap_block_state56_pp0_stage0_iter5;
wire    ap_block_state57_pp0_stage0_iter6;
reg    ap_block_state58_pp0_stage0_iter7;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] exitcond2_reg_1440_pp0_iter2_reg;
reg   [0:0] exitcond2_reg_1440_pp0_iter3_reg;
reg   [0:0] exitcond2_reg_1440_pp0_iter4_reg;
reg   [0:0] exitcond2_reg_1440_pp0_iter5_reg;
wire   [11:0] i_fu_1123_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [1:0] tmp_83_fu_1129_p1;
reg   [1:0] tmp_83_reg_1449;
wire   [23:0] index_2_fu_1151_p2;
reg   [31:0] buf_addr_reg_1479;
wire   [15:0] tmp_22_fu_1186_p6;
reg   [15:0] tmp_22_reg_1485;
wire   [39:0] p_0285_2_fu_1275_p3;
wire    ap_CS_fsm_state59;
wire   [23:0] indvars_iv_next_fu_1283_p2;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state51;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg   [8:0] mem_0_address0;
reg    mem_0_ce0;
reg    mem_0_we0;
wire   [10:0] mem_0_q0;
reg   [8:0] mem_1_address0;
reg    mem_1_ce0;
reg    mem_1_we0;
wire   [10:0] mem_1_q0;
reg   [8:0] mem_2_address0;
reg    mem_2_ce0;
reg    mem_2_we0;
wire   [10:0] mem_2_q0;
reg   [8:0] mem_3_address0;
reg    mem_3_ce0;
reg    mem_3_we0;
wire   [10:0] mem_3_q0;
wire    grp_mandel_calc_fu_337_ap_start;
wire    grp_mandel_calc_fu_337_ap_done;
wire    grp_mandel_calc_fu_337_ap_idle;
wire    grp_mandel_calc_fu_337_ap_ready;
wire   [10:0] grp_mandel_calc_fu_337_ap_return;
wire    grp_mandel_calc_fu_345_ap_start;
wire    grp_mandel_calc_fu_345_ap_done;
wire    grp_mandel_calc_fu_345_ap_idle;
wire    grp_mandel_calc_fu_345_ap_ready;
wire   [10:0] grp_mandel_calc_fu_345_ap_return;
wire    grp_mandel_calc_fu_353_ap_start;
wire    grp_mandel_calc_fu_353_ap_done;
wire    grp_mandel_calc_fu_353_ap_idle;
wire    grp_mandel_calc_fu_353_ap_ready;
wire   [10:0] grp_mandel_calc_fu_353_ap_return;
wire    grp_mandel_calc_fu_361_ap_start;
wire    grp_mandel_calc_fu_361_ap_done;
wire    grp_mandel_calc_fu_361_ap_idle;
wire    grp_mandel_calc_fu_361_ap_ready;
wire   [10:0] grp_mandel_calc_fu_361_ap_return;
reg   [23:0] indvars_iv_reg_262;
reg   [39:0] p_Val2_28_reg_272;
reg   [11:0] t_V_1_reg_282;
reg   [23:0] index_reg_293;
reg   [11:0] tmp_V_1_reg_305;
wire    ap_CS_fsm_state50;
reg    ap_block_state50_on_subcall_done;
wire   [0:0] exitcond_fu_507_p2;
reg    grp_mandel_calc_fu_337_ap_start_reg;
wire    ap_CS_fsm_state49;
reg    grp_mandel_calc_fu_345_ap_start_reg;
reg    grp_mandel_calc_fu_353_ap_start_reg;
reg    grp_mandel_calc_fu_361_ap_start_reg;
wire   [63:0] newIndex3_fu_1110_p1;
wire   [63:0] newIndex1_fu_1143_p1;
wire   [63:0] tmp_35_fu_1157_p1;
reg    ap_reg_ioackin_buf_r_AWREADY;
reg    ap_block_pp0_stage0_01001;
reg    ap_reg_ioackin_buf_r_WREADY;
wire  signed [39:0] rhs_V_fu_373_p0;
wire  signed [40:0] lhs_V_fu_369_p1;
wire  signed [40:0] rhs_V_fu_373_p1;
wire   [40:0] grp_fu_387_p0;
wire   [12:0] grp_fu_387_p1;
wire   [40:0] grp_fu_387_p2;
wire   [0:0] p_Result_20_fu_405_p3;
wire   [0:0] p_Result_s_fu_393_p3;
wire   [0:0] tmp_s_fu_413_p2;
wire   [0:0] signbit_i_i_i_i27_0_s_fu_431_p2;
wire   [0:0] brmerge_fu_425_p2;
wire   [39:0] p_Val2_27_fu_401_p1;
wire   [0:0] underflow_fu_419_p2;
wire   [0:0] brmerge1_fu_437_p2;
wire   [39:0] p_mux_fu_443_p3;
wire   [39:0] p_s_fu_451_p3;
wire   [13:0] p_shl_fu_470_p3;
wire   [13:0] lhs_V_7_cast_fu_467_p1;
wire   [13:0] ret_V_fu_477_p2;
wire  signed [39:0] delta_V_fu_459_p3;
wire   [11:0] r_V_s_fu_527_p0;
wire  signed [39:0] r_V_s_fu_527_p1;
wire   [11:0] pix_x_V_s_fu_546_p2;
wire   [11:0] r_V_23_1_fu_556_p0;
wire  signed [39:0] r_V_23_1_fu_556_p1;
wire   [11:0] pix_x_V_1_fu_565_p2;
wire   [11:0] r_V_23_2_fu_575_p0;
wire  signed [39:0] r_V_23_2_fu_575_p1;
wire   [11:0] pix_x_V_2_fu_584_p2;
wire   [11:0] r_V_23_3_fu_594_p0;
wire  signed [39:0] r_V_23_3_fu_594_p1;
wire   [51:0] ret_V_s_fu_614_p2;
wire   [39:0] p_Val2_8_fu_626_p2;
wire   [11:0] tmp_18_fu_638_p4;
wire   [0:0] tmp_70_fu_630_p3;
wire   [0:0] p_not_fu_648_p2;
wire   [0:0] tmp_69_fu_618_p3;
wire   [0:0] brmerge2_fu_654_p2;
wire   [0:0] tmp_32_fu_660_p2;
wire   [0:0] p_not2_fu_678_p2;
wire   [0:0] newsignbit_i_i_i_i_fu_672_p2;
wire   [0:0] brmerge3_fu_684_p2;
wire   [0:0] underflow_6_fu_690_p2;
wire   [0:0] overflow_6_fu_666_p2;
wire   [0:0] p_707_not_fu_702_p2;
wire   [0:0] brmerge4_fu_696_p2;
wire   [0:0] brmerge5_fu_708_p2;
wire   [39:0] p_mux6_fu_714_p3;
wire   [39:0] p_9_fu_722_p3;
wire   [51:0] ret_V_18_1_fu_738_p2;
wire   [39:0] p_Val2_8_1_fu_750_p2;
wire   [11:0] tmp_19_fu_762_p4;
wire   [0:0] tmp_73_fu_754_p3;
wire   [0:0] p_not_1_fu_772_p2;
wire   [0:0] tmp_72_fu_742_p3;
wire   [0:0] brmerge28_1_fu_778_p2;
wire   [0:0] tmp_77_1_fu_784_p2;
wire   [0:0] p_not2_1_fu_802_p2;
wire   [0:0] newsignbit_i_i_i_i_0_1_fu_796_p2;
wire   [0:0] brmerge29_1_fu_808_p2;
wire   [0:0] underflow_6_1_fu_814_p2;
wire   [0:0] overflow_6_1_fu_790_p2;
wire   [0:0] p_707_not_1_fu_826_p2;
wire   [0:0] brmerge30_1_fu_820_p2;
wire   [0:0] brmerge31_1_fu_832_p2;
wire   [39:0] p_mux6_1_fu_838_p3;
wire   [39:0] p_9_1_fu_846_p3;
wire   [51:0] ret_V_18_2_fu_862_p2;
wire   [39:0] p_Val2_8_2_fu_874_p2;
wire   [11:0] tmp_20_fu_886_p4;
wire   [0:0] tmp_76_fu_878_p3;
wire   [0:0] p_not_2_fu_896_p2;
wire   [0:0] tmp_75_fu_866_p3;
wire   [0:0] brmerge28_2_fu_902_p2;
wire   [0:0] tmp_77_2_fu_908_p2;
wire   [0:0] p_not2_2_fu_926_p2;
wire   [0:0] newsignbit_i_i_i_i_0_2_fu_920_p2;
wire   [0:0] brmerge29_2_fu_932_p2;
wire   [0:0] underflow_6_2_fu_938_p2;
wire   [0:0] overflow_6_2_fu_914_p2;
wire   [0:0] p_707_not_2_fu_950_p2;
wire   [0:0] brmerge30_2_fu_944_p2;
wire   [0:0] brmerge31_2_fu_956_p2;
wire   [39:0] p_mux6_2_fu_962_p3;
wire   [39:0] p_9_2_fu_970_p3;
wire   [51:0] ret_V_18_3_fu_986_p2;
wire   [39:0] p_Val2_8_3_fu_998_p2;
wire   [11:0] tmp_21_fu_1010_p4;
wire   [0:0] tmp_79_fu_1002_p3;
wire   [0:0] p_not_3_fu_1020_p2;
wire   [0:0] tmp_78_fu_990_p3;
wire   [0:0] brmerge28_3_fu_1026_p2;
wire   [0:0] tmp_77_3_fu_1032_p2;
wire   [0:0] p_not2_3_fu_1050_p2;
wire   [0:0] newsignbit_i_i_i_i_0_3_fu_1044_p2;
wire   [0:0] brmerge29_3_fu_1056_p2;
wire   [0:0] underflow_6_3_fu_1062_p2;
wire   [0:0] overflow_6_3_fu_1038_p2;
wire   [0:0] p_707_not_3_fu_1074_p2;
wire   [0:0] brmerge30_3_fu_1068_p2;
wire   [0:0] brmerge31_3_fu_1080_p2;
wire   [39:0] p_mux6_3_fu_1086_p3;
wire   [39:0] p_9_3_fu_1094_p3;
wire   [9:0] newIndex_fu_1133_p4;
wire   [15:0] tmp_22_fu_1186_p1;
wire   [15:0] tmp_22_fu_1186_p2;
wire   [15:0] tmp_22_fu_1186_p3;
wire   [15:0] tmp_22_fu_1186_p4;
wire   [31:0] tmp_22_fu_1186_p5;
wire  signed [40:0] lhs_V_3_fu_1200_p1;
wire   [40:0] ret_V_14_fu_1204_p2;
wire   [0:0] p_Result_22_fu_1221_p3;
wire   [0:0] p_Result_21_fu_1209_p3;
wire   [0:0] tmp_34_fu_1229_p2;
wire   [0:0] signbit_i_i_0_not_fu_1247_p2;
wire   [0:0] brmerge6_fu_1241_p2;
wire   [39:0] y_V_fu_1217_p1;
wire   [0:0] underflow_7_fu_1235_p2;
wire   [0:0] brmerge7_fu_1253_p2;
wire   [39:0] p_mux7_fu_1259_p3;
wire   [39:0] p_2_fu_1267_p3;
reg    grp_fu_387_ap_start;
wire    grp_fu_387_ap_done;
reg   [51:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire   [40:0] grp_fu_387_p10;
wire   [51:0] r_V_23_1_fu_556_p00;
wire   [51:0] r_V_23_2_fu_575_p00;
wire   [51:0] r_V_23_3_fu_594_p00;
wire   [51:0] r_V_s_fu_527_p00;
reg    ap_condition_1502;

// power-on initialization
initial begin
#0 ap_CS_fsm = 52'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 grp_mandel_calc_fu_337_ap_start_reg = 1'b0;
#0 grp_mandel_calc_fu_345_ap_start_reg = 1'b0;
#0 grp_mandel_calc_fu_353_ap_start_reg = 1'b0;
#0 grp_mandel_calc_fu_361_ap_start_reg = 1'b0;
#0 ap_reg_ioackin_buf_r_AWREADY = 1'b0;
#0 ap_reg_ioackin_buf_r_WREADY = 1'b0;
end

calc_in_parms_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_IN_PARMS_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_IN_PARMS_DATA_WIDTH ))
calc_in_parms_s_axi_U(
    .AWVALID(s_axi_in_parms_AWVALID),
    .AWREADY(s_axi_in_parms_AWREADY),
    .AWADDR(s_axi_in_parms_AWADDR),
    .WVALID(s_axi_in_parms_WVALID),
    .WREADY(s_axi_in_parms_WREADY),
    .WDATA(s_axi_in_parms_WDATA),
    .WSTRB(s_axi_in_parms_WSTRB),
    .ARVALID(s_axi_in_parms_ARVALID),
    .ARREADY(s_axi_in_parms_ARREADY),
    .ARADDR(s_axi_in_parms_ARADDR),
    .RVALID(s_axi_in_parms_RVALID),
    .RREADY(s_axi_in_parms_RREADY),
    .RDATA(s_axi_in_parms_RDATA),
    .RRESP(s_axi_in_parms_RRESP),
    .BVALID(s_axi_in_parms_BVALID),
    .BREADY(s_axi_in_parms_BREADY),
    .BRESP(s_axi_in_parms_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle),
    .X0_V(X0_V),
    .Y0_V(Y0_V),
    .X1_V(X1_V),
    .width_V(width_V)
);

calc_buf_r_m_axi #(
    .CONSERVATIVE( 0 ),
    .USER_DW( 16 ),
    .USER_AW( 32 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_BUF_R_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_BUF_R_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_BUF_R_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_BUF_R_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_BUF_R_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_BUF_R_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_BUF_R_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_BUF_R_BUSER_WIDTH ),
    .C_TARGET_ADDR( C_M_AXI_BUF_R_TARGET_ADDR ),
    .C_USER_VALUE( C_M_AXI_BUF_R_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_BUF_R_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_BUF_R_CACHE_VALUE ))
calc_buf_r_m_axi_U(
    .AWVALID(m_axi_buf_r_AWVALID),
    .AWREADY(m_axi_buf_r_AWREADY),
    .AWADDR(m_axi_buf_r_AWADDR),
    .AWID(m_axi_buf_r_AWID),
    .AWLEN(m_axi_buf_r_AWLEN),
    .AWSIZE(m_axi_buf_r_AWSIZE),
    .AWBURST(m_axi_buf_r_AWBURST),
    .AWLOCK(m_axi_buf_r_AWLOCK),
    .AWCACHE(m_axi_buf_r_AWCACHE),
    .AWPROT(m_axi_buf_r_AWPROT),
    .AWQOS(m_axi_buf_r_AWQOS),
    .AWREGION(m_axi_buf_r_AWREGION),
    .AWUSER(m_axi_buf_r_AWUSER),
    .WVALID(m_axi_buf_r_WVALID),
    .WREADY(m_axi_buf_r_WREADY),
    .WDATA(m_axi_buf_r_WDATA),
    .WSTRB(m_axi_buf_r_WSTRB),
    .WLAST(m_axi_buf_r_WLAST),
    .WID(m_axi_buf_r_WID),
    .WUSER(m_axi_buf_r_WUSER),
    .ARVALID(m_axi_buf_r_ARVALID),
    .ARREADY(m_axi_buf_r_ARREADY),
    .ARADDR(m_axi_buf_r_ARADDR),
    .ARID(m_axi_buf_r_ARID),
    .ARLEN(m_axi_buf_r_ARLEN),
    .ARSIZE(m_axi_buf_r_ARSIZE),
    .ARBURST(m_axi_buf_r_ARBURST),
    .ARLOCK(m_axi_buf_r_ARLOCK),
    .ARCACHE(m_axi_buf_r_ARCACHE),
    .ARPROT(m_axi_buf_r_ARPROT),
    .ARQOS(m_axi_buf_r_ARQOS),
    .ARREGION(m_axi_buf_r_ARREGION),
    .ARUSER(m_axi_buf_r_ARUSER),
    .RVALID(m_axi_buf_r_RVALID),
    .RREADY(m_axi_buf_r_RREADY),
    .RDATA(m_axi_buf_r_RDATA),
    .RLAST(m_axi_buf_r_RLAST),
    .RID(m_axi_buf_r_RID),
    .RUSER(m_axi_buf_r_RUSER),
    .RRESP(m_axi_buf_r_RRESP),
    .BVALID(m_axi_buf_r_BVALID),
    .BREADY(m_axi_buf_r_BREADY),
    .BRESP(m_axi_buf_r_BRESP),
    .BID(m_axi_buf_r_BID),
    .BUSER(m_axi_buf_r_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(1'b0),
    .I_ARREADY(buf_r_ARREADY),
    .I_ARADDR(32'd0),
    .I_ARID(1'd0),
    .I_ARLEN(32'd0),
    .I_ARSIZE(3'd0),
    .I_ARLOCK(2'd0),
    .I_ARCACHE(4'd0),
    .I_ARQOS(4'd0),
    .I_ARPROT(3'd0),
    .I_ARUSER(1'd0),
    .I_ARBURST(2'd0),
    .I_ARREGION(4'd0),
    .I_RVALID(buf_r_RVALID),
    .I_RREADY(1'b0),
    .I_RDATA(buf_r_RDATA),
    .I_RID(buf_r_RID),
    .I_RUSER(buf_r_RUSER),
    .I_RRESP(buf_r_RRESP),
    .I_RLAST(buf_r_RLAST),
    .I_AWVALID(buf_r_AWVALID),
    .I_AWREADY(buf_r_AWREADY),
    .I_AWADDR(buf_addr_reg_1479),
    .I_AWID(1'd0),
    .I_AWLEN(32'd1),
    .I_AWSIZE(3'd0),
    .I_AWLOCK(2'd0),
    .I_AWCACHE(4'd0),
    .I_AWQOS(4'd0),
    .I_AWPROT(3'd0),
    .I_AWUSER(1'd0),
    .I_AWBURST(2'd0),
    .I_AWREGION(4'd0),
    .I_WVALID(buf_r_WVALID),
    .I_WREADY(buf_r_WREADY),
    .I_WDATA(tmp_22_reg_1485),
    .I_WID(1'd0),
    .I_WUSER(1'd0),
    .I_WLAST(1'b0),
    .I_WSTRB(2'd3),
    .I_BVALID(buf_r_BVALID),
    .I_BREADY(buf_r_BREADY),
    .I_BRESP(buf_r_BRESP),
    .I_BID(buf_r_BID),
    .I_BUSER(buf_r_BUSER)
);

calc_mem_0 #(
    .DataWidth( 11 ),
    .AddressRange( 480 ),
    .AddressWidth( 9 ))
mem_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(mem_0_address0),
    .ce0(mem_0_ce0),
    .we0(mem_0_we0),
    .d0(grp_mandel_calc_fu_337_ap_return),
    .q0(mem_0_q0)
);

calc_mem_0 #(
    .DataWidth( 11 ),
    .AddressRange( 480 ),
    .AddressWidth( 9 ))
mem_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(mem_1_address0),
    .ce0(mem_1_ce0),
    .we0(mem_1_we0),
    .d0(grp_mandel_calc_fu_345_ap_return),
    .q0(mem_1_q0)
);

calc_mem_0 #(
    .DataWidth( 11 ),
    .AddressRange( 480 ),
    .AddressWidth( 9 ))
mem_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(mem_2_address0),
    .ce0(mem_2_ce0),
    .we0(mem_2_we0),
    .d0(grp_mandel_calc_fu_353_ap_return),
    .q0(mem_2_q0)
);

calc_mem_0 #(
    .DataWidth( 11 ),
    .AddressRange( 480 ),
    .AddressWidth( 9 ))
mem_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(mem_3_address0),
    .ce0(mem_3_ce0),
    .we0(mem_3_we0),
    .d0(grp_mandel_calc_fu_361_ap_return),
    .q0(mem_3_q0)
);

mandel_calc grp_mandel_calc_fu_337(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_mandel_calc_fu_337_ap_start),
    .ap_done(grp_mandel_calc_fu_337_ap_done),
    .ap_idle(grp_mandel_calc_fu_337_ap_idle),
    .ap_ready(grp_mandel_calc_fu_337_ap_ready),
    .x_in_V(p_0_reg_1420),
    .y_in_V(p_Val2_28_reg_272),
    .ap_return(grp_mandel_calc_fu_337_ap_return)
);

mandel_calc grp_mandel_calc_fu_345(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_mandel_calc_fu_345_ap_start),
    .ap_done(grp_mandel_calc_fu_345_ap_done),
    .ap_idle(grp_mandel_calc_fu_345_ap_idle),
    .ap_ready(grp_mandel_calc_fu_345_ap_ready),
    .x_in_V(p_0_1_reg_1425),
    .y_in_V(p_Val2_28_reg_272),
    .ap_return(grp_mandel_calc_fu_345_ap_return)
);

mandel_calc grp_mandel_calc_fu_353(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_mandel_calc_fu_353_ap_start),
    .ap_done(grp_mandel_calc_fu_353_ap_done),
    .ap_idle(grp_mandel_calc_fu_353_ap_idle),
    .ap_ready(grp_mandel_calc_fu_353_ap_ready),
    .x_in_V(p_0_2_reg_1430),
    .y_in_V(p_Val2_28_reg_272),
    .ap_return(grp_mandel_calc_fu_353_ap_return)
);

mandel_calc grp_mandel_calc_fu_361(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_mandel_calc_fu_361_ap_start),
    .ap_done(grp_mandel_calc_fu_361_ap_done),
    .ap_idle(grp_mandel_calc_fu_361_ap_idle),
    .ap_ready(grp_mandel_calc_fu_361_ap_ready),
    .x_in_V(p_0_3_reg_1435),
    .y_in_V(p_Val2_28_reg_272),
    .ap_return(grp_mandel_calc_fu_361_ap_return)
);

calc_sdiv_41ns_13dEe #(
    .ID( 1 ),
    .NUM_STAGE( 45 ),
    .din0_WIDTH( 41 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 41 ))
calc_sdiv_41ns_13dEe_U10(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .start(grp_fu_387_ap_start),
    .done(grp_fu_387_ap_done),
    .din0(grp_fu_387_p0),
    .din1(grp_fu_387_p1),
    .ce(1'b1),
    .dout(grp_fu_387_p2)
);

calc_mux_432_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 32 ),
    .dout_WIDTH( 16 ))
calc_mux_432_16_1_1_U11(
    .din0(tmp_22_fu_1186_p1),
    .din1(tmp_22_fu_1186_p2),
    .din2(tmp_22_fu_1186_p3),
    .din3(tmp_22_fu_1186_p4),
    .din4(tmp_22_fu_1186_p5),
    .dout(tmp_22_fu_1186_p6)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state51) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((exitcond3_fu_518_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state47))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state51)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state51);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end else if (((exitcond3_fu_518_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state47))) begin
            ap_enable_reg_pp0_iter7 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ioackin_buf_r_AWREADY <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_1502)) begin
            if ((1'b0 == ap_block_pp0_stage0_11001)) begin
                ap_reg_ioackin_buf_r_AWREADY <= 1'b0;
            end else if (((1'b0 == ap_block_pp0_stage0_01001) & (buf_r_AWREADY == 1'b1))) begin
                ap_reg_ioackin_buf_r_AWREADY <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ioackin_buf_r_WREADY <= 1'b0;
    end else begin
        if (((ap_enable_reg_pp0_iter2 == 1'b1) & (exitcond2_reg_1440_pp0_iter1_reg == 1'd0))) begin
            if ((1'b0 == ap_block_pp0_stage0_11001)) begin
                ap_reg_ioackin_buf_r_WREADY <= 1'b0;
            end else if (((1'b0 == ap_block_pp0_stage0_01001) & (buf_r_WREADY == 1'b1))) begin
                ap_reg_ioackin_buf_r_WREADY <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_mandel_calc_fu_337_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state49)) begin
            grp_mandel_calc_fu_337_ap_start_reg <= 1'b1;
        end else if ((grp_mandel_calc_fu_337_ap_ready == 1'b1)) begin
            grp_mandel_calc_fu_337_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_mandel_calc_fu_345_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state49)) begin
            grp_mandel_calc_fu_345_ap_start_reg <= 1'b1;
        end else if ((grp_mandel_calc_fu_345_ap_ready == 1'b1)) begin
            grp_mandel_calc_fu_345_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_mandel_calc_fu_353_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state49)) begin
            grp_mandel_calc_fu_353_ap_start_reg <= 1'b1;
        end else if ((grp_mandel_calc_fu_353_ap_ready == 1'b1)) begin
            grp_mandel_calc_fu_353_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_mandel_calc_fu_361_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state49)) begin
            grp_mandel_calc_fu_361_ap_start_reg <= 1'b1;
        end else if ((grp_mandel_calc_fu_361_ap_ready == 1'b1)) begin
            grp_mandel_calc_fu_361_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond3_fu_518_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state47))) begin
        i_op_assign_reg_326 <= 12'd0;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond2_fu_1117_p2 == 1'd0))) begin
        i_op_assign_reg_326 <= i_fu_1123_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond3_fu_518_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state47))) begin
        index_1_reg_316 <= index_reg_293;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond2_fu_1117_p2 == 1'd0))) begin
        index_1_reg_316 <= index_2_fu_1151_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state59)) begin
        index_reg_293 <= index_3_reg_1415;
    end else if ((1'b1 == ap_CS_fsm_state45)) begin
        index_reg_293 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state59)) begin
        indvars_iv_reg_262 <= indvars_iv_next_fu_1283_p2;
    end else if ((1'b1 == ap_CS_fsm_state45)) begin
        indvars_iv_reg_262 <= tmp_2_cast_fu_493_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state59)) begin
        p_Val2_28_reg_272 <= p_0285_2_fu_1275_p3;
    end else if ((1'b1 == ap_CS_fsm_state45)) begin
        p_Val2_28_reg_272 <= Y0_V_read_reg_1296;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state59)) begin
        t_V_1_reg_282 <= line_V_reg_1356;
    end else if ((1'b1 == ap_CS_fsm_state45)) begin
        t_V_1_reg_282 <= 12'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state46) & (exitcond_fu_507_p2 == 1'd0))) begin
        tmp_V_1_reg_305 <= 12'd0;
    end else if (((1'b0 == ap_block_state50_on_subcall_done) & (1'b1 == ap_CS_fsm_state50))) begin
        tmp_V_1_reg_305 <= pix_x_V_3_reg_1410;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        X0_V_read_reg_1301 <= X0_V;
        Y0_V_read_reg_1296 <= Y0_V;
        width_V_read_reg_1288 <= width_V;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond2_fu_1117_p2 == 1'd0))) begin
        buf_addr_reg_1479[23 : 0] <= tmp_35_fu_1157_p1[23 : 0];
        tmp_83_reg_1449 <= tmp_83_fu_1129_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exitcond2_reg_1440 <= exitcond2_fu_1117_p2;
        exitcond2_reg_1440_pp0_iter1_reg <= exitcond2_reg_1440;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        exitcond2_reg_1440_pp0_iter2_reg <= exitcond2_reg_1440_pp0_iter1_reg;
        exitcond2_reg_1440_pp0_iter3_reg <= exitcond2_reg_1440_pp0_iter2_reg;
        exitcond2_reg_1440_pp0_iter4_reg <= exitcond2_reg_1440_pp0_iter3_reg;
        exitcond2_reg_1440_pp0_iter5_reg <= exitcond2_reg_1440_pp0_iter4_reg;
        exitcond2_reg_1440_pp0_iter6_reg <= exitcond2_reg_1440_pp0_iter5_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state45)) begin
        height_V_reg_1320 <= {{ret_V_fu_477_p2[13:2]}};
        lhs_V_8_cast_reg_1340 <= lhs_V_8_cast_fu_500_p1;
        rhs_V_4_reg_1348 <= rhs_V_4_fu_503_p1;
        tmp_2_cast_reg_1325[11 : 0] <= tmp_2_cast_fu_493_p1[11 : 0];
        tmp_31_reg_1332 <= tmp_31_fu_496_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond3_fu_518_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state47))) begin
        index_3_reg_1415 <= index_3_fu_609_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state46)) begin
        line_V_reg_1356 <= line_V_fu_512_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state47) & (exitcond3_fu_518_p2 == 1'd0))) begin
        newIndex2_reg_1375 <= {{tmp_V_1_reg_305[11:2]}};
        pix_x_V_3_reg_1410 <= pix_x_V_3_fu_603_p2;
        r_V_23_1_reg_1380 <= r_V_23_1_fu_556_p2;
        r_V_23_2_reg_1390 <= r_V_23_2_fu_575_p2;
        r_V_23_3_reg_1400 <= r_V_23_3_fu_594_p2;
        r_V_s_reg_1365 <= r_V_s_fu_527_p2;
        tmp_68_reg_1370 <= tmp_68_fu_532_p1;
        tmp_71_reg_1385 <= tmp_71_fu_561_p1;
        tmp_74_reg_1395 <= tmp_74_fu_580_p1;
        tmp_77_reg_1405 <= tmp_77_fu_599_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state48)) begin
        p_0_1_reg_1425 <= p_0_1_fu_854_p3;
        p_0_2_reg_1430 <= p_0_2_fu_978_p3;
        p_0_3_reg_1435 <= p_0_3_fu_1102_p3;
        p_0_reg_1420 <= p_0_fu_730_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond2_reg_1440 == 1'd0))) begin
        tmp_22_reg_1485 <= tmp_22_fu_1186_p6;
    end
end

always @ (*) begin
    if ((exitcond2_fu_1117_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state51 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state51 = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond_fu_507_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state46))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond_fu_507_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state46))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((ap_reg_ioackin_buf_r_AWREADY == 1'b0)) begin
        ap_sig_ioackin_buf_r_AWREADY = buf_r_AWREADY;
    end else begin
        ap_sig_ioackin_buf_r_AWREADY = 1'b1;
    end
end

always @ (*) begin
    if ((ap_reg_ioackin_buf_r_WREADY == 1'b0)) begin
        ap_sig_ioackin_buf_r_WREADY = buf_r_WREADY;
    end else begin
        ap_sig_ioackin_buf_r_WREADY = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_reg_ioackin_buf_r_AWREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond2_reg_1440 == 1'd0))) begin
        buf_r_AWVALID = 1'b1;
    end else begin
        buf_r_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (exitcond2_reg_1440_pp0_iter6_reg == 1'd0))) begin
        buf_r_BREADY = 1'b1;
    end else begin
        buf_r_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_reg_ioackin_buf_r_WREADY == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (exitcond2_reg_1440_pp0_iter1_reg == 1'd0))) begin
        buf_r_WVALID = 1'b1;
    end else begin
        buf_r_WVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond2_reg_1440 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        buf_r_blk_n_AW = m_axi_buf_r_AWREADY;
    end else begin
        buf_r_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b1) & (exitcond2_reg_1440_pp0_iter6_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        buf_r_blk_n_B = m_axi_buf_r_BVALID;
    end else begin
        buf_r_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (exitcond2_reg_1440_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        buf_r_blk_n_W = m_axi_buf_r_WREADY;
    end else begin
        buf_r_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        grp_fu_387_ap_start = 1'b1;
    end else begin
        grp_fu_387_ap_start = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        mem_0_address0 = newIndex1_fu_1143_p1;
    end else if ((1'b1 == ap_CS_fsm_state50)) begin
        mem_0_address0 = newIndex3_fu_1110_p1;
    end else begin
        mem_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state50_on_subcall_done) & (1'b1 == ap_CS_fsm_state50)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        mem_0_ce0 = 1'b1;
    end else begin
        mem_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state50_on_subcall_done) & (1'b1 == ap_CS_fsm_state50))) begin
        mem_0_we0 = 1'b1;
    end else begin
        mem_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        mem_1_address0 = newIndex1_fu_1143_p1;
    end else if ((1'b1 == ap_CS_fsm_state50)) begin
        mem_1_address0 = newIndex3_fu_1110_p1;
    end else begin
        mem_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state50_on_subcall_done) & (1'b1 == ap_CS_fsm_state50)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        mem_1_ce0 = 1'b1;
    end else begin
        mem_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state50_on_subcall_done) & (1'b1 == ap_CS_fsm_state50))) begin
        mem_1_we0 = 1'b1;
    end else begin
        mem_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        mem_2_address0 = newIndex1_fu_1143_p1;
    end else if ((1'b1 == ap_CS_fsm_state50)) begin
        mem_2_address0 = newIndex3_fu_1110_p1;
    end else begin
        mem_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state50_on_subcall_done) & (1'b1 == ap_CS_fsm_state50)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        mem_2_ce0 = 1'b1;
    end else begin
        mem_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state50_on_subcall_done) & (1'b1 == ap_CS_fsm_state50))) begin
        mem_2_we0 = 1'b1;
    end else begin
        mem_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        mem_3_address0 = newIndex1_fu_1143_p1;
    end else if ((1'b1 == ap_CS_fsm_state50)) begin
        mem_3_address0 = newIndex3_fu_1110_p1;
    end else begin
        mem_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state50_on_subcall_done) & (1'b1 == ap_CS_fsm_state50)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        mem_3_ce0 = 1'b1;
    end else begin
        mem_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state50_on_subcall_done) & (1'b1 == ap_CS_fsm_state50))) begin
        mem_3_we0 = 1'b1;
    end else begin
        mem_3_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            if (((exitcond_fu_507_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state46))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state47;
            end
        end
        ap_ST_fsm_state47 : begin
            if (((exitcond3_fu_518_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state47))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state48;
            end
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state50;
        end
        ap_ST_fsm_state50 : begin
            if (((1'b0 == ap_block_state50_on_subcall_done) & (1'b1 == ap_CS_fsm_state50))) begin
                ap_NS_fsm = ap_ST_fsm_state47;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state50;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((1'b0 == ap_block_pp0_stage0_subdone) & (exitcond2_fu_1117_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0)) & ~((ap_enable_reg_pp0_iter6 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter7 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((1'b0 == ap_block_pp0_stage0_subdone) & (exitcond2_fu_1117_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0)) | ((ap_enable_reg_pp0_iter6 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter7 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state59;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state59 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd50];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state45 = ap_CS_fsm[32'd44];

assign ap_CS_fsm_state46 = ap_CS_fsm[32'd45];

assign ap_CS_fsm_state47 = ap_CS_fsm[32'd46];

assign ap_CS_fsm_state48 = ap_CS_fsm[32'd47];

assign ap_CS_fsm_state49 = ap_CS_fsm[32'd48];

assign ap_CS_fsm_state50 = ap_CS_fsm[32'd49];

assign ap_CS_fsm_state59 = ap_CS_fsm[32'd51];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((buf_r_BVALID == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b1) & (exitcond2_reg_1440_pp0_iter6_reg == 1'd0));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((buf_r_BVALID == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b1) & (exitcond2_reg_1440_pp0_iter6_reg == 1'd0)) | ((1'b1 == ap_block_state53_io) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b1 == ap_block_state52_io) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((buf_r_BVALID == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b1) & (exitcond2_reg_1440_pp0_iter6_reg == 1'd0)) | ((1'b1 == ap_block_state53_io) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b1 == ap_block_state52_io) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_state50_on_subcall_done = ((grp_mandel_calc_fu_361_ap_done == 1'b0) | (grp_mandel_calc_fu_353_ap_done == 1'b0) | (grp_mandel_calc_fu_345_ap_done == 1'b0) | (grp_mandel_calc_fu_337_ap_done == 1'b0));
end

assign ap_block_state51_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state52_io = ((ap_sig_ioackin_buf_r_AWREADY == 1'b0) & (exitcond2_reg_1440 == 1'd0));
end

assign ap_block_state52_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state53_io = ((ap_sig_ioackin_buf_r_WREADY == 1'b0) & (exitcond2_reg_1440_pp0_iter1_reg == 1'd0));
end

assign ap_block_state53_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state54_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state55_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state56_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state57_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state58_pp0_stage0_iter7 = ((buf_r_BVALID == 1'b0) & (exitcond2_reg_1440_pp0_iter6_reg == 1'd0));
end

always @ (*) begin
    ap_condition_1502 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond2_reg_1440 == 1'd0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign brmerge1_fu_437_p2 = (signbit_i_i_i_i27_0_s_fu_431_p2 | p_Result_20_fu_405_p3);

assign brmerge28_1_fu_778_p2 = (tmp_73_fu_754_p3 | p_not_1_fu_772_p2);

assign brmerge28_2_fu_902_p2 = (tmp_76_fu_878_p3 | p_not_2_fu_896_p2);

assign brmerge28_3_fu_1026_p2 = (tmp_79_fu_1002_p3 | p_not_3_fu_1020_p2);

assign brmerge29_1_fu_808_p2 = (p_not2_1_fu_802_p2 | newsignbit_i_i_i_i_0_1_fu_796_p2);

assign brmerge29_2_fu_932_p2 = (p_not2_2_fu_926_p2 | newsignbit_i_i_i_i_0_2_fu_920_p2);

assign brmerge29_3_fu_1056_p2 = (p_not2_3_fu_1050_p2 | newsignbit_i_i_i_i_0_3_fu_1044_p2);

assign brmerge2_fu_654_p2 = (tmp_70_fu_630_p3 | p_not_fu_648_p2);

assign brmerge30_1_fu_820_p2 = (underflow_6_1_fu_814_p2 | overflow_6_1_fu_790_p2);

assign brmerge30_2_fu_944_p2 = (underflow_6_2_fu_938_p2 | overflow_6_2_fu_914_p2);

assign brmerge30_3_fu_1068_p2 = (underflow_6_3_fu_1062_p2 | overflow_6_3_fu_1038_p2);

assign brmerge31_1_fu_832_p2 = (p_707_not_1_fu_826_p2 | overflow_6_1_fu_790_p2);

assign brmerge31_2_fu_956_p2 = (p_707_not_2_fu_950_p2 | overflow_6_2_fu_914_p2);

assign brmerge31_3_fu_1080_p2 = (p_707_not_3_fu_1074_p2 | overflow_6_3_fu_1038_p2);

assign brmerge3_fu_684_p2 = (p_not2_fu_678_p2 | newsignbit_i_i_i_i_fu_672_p2);

assign brmerge4_fu_696_p2 = (underflow_6_fu_690_p2 | overflow_6_fu_666_p2);

assign brmerge5_fu_708_p2 = (p_707_not_fu_702_p2 | overflow_6_fu_666_p2);

assign brmerge6_fu_1241_p2 = (p_Result_22_fu_1221_p3 ^ p_Result_21_fu_1209_p3);

assign brmerge7_fu_1253_p2 = (signbit_i_i_0_not_fu_1247_p2 | p_Result_22_fu_1221_p3);

assign brmerge_fu_425_p2 = (p_Result_s_fu_393_p3 ^ p_Result_20_fu_405_p3);

assign delta_V_fu_459_p3 = ((brmerge1_fu_437_p2[0:0] === 1'b1) ? p_mux_fu_443_p3 : p_s_fu_451_p3);

assign exitcond2_fu_1117_p2 = ((index_1_reg_316 == indvars_iv_reg_262) ? 1'b1 : 1'b0);

assign exitcond3_fu_518_p2 = ((tmp_V_1_reg_305 == width_V_read_reg_1288) ? 1'b1 : 1'b0);

assign exitcond_fu_507_p2 = ((t_V_1_reg_282 == height_V_reg_1320) ? 1'b1 : 1'b0);

assign grp_fu_387_p0 = ($signed(lhs_V_fu_369_p1) - $signed(rhs_V_fu_373_p1));

assign grp_fu_387_p1 = grp_fu_387_p10;

assign grp_fu_387_p10 = width_V;

assign grp_mandel_calc_fu_337_ap_start = grp_mandel_calc_fu_337_ap_start_reg;

assign grp_mandel_calc_fu_345_ap_start = grp_mandel_calc_fu_345_ap_start_reg;

assign grp_mandel_calc_fu_353_ap_start = grp_mandel_calc_fu_353_ap_start_reg;

assign grp_mandel_calc_fu_361_ap_start = grp_mandel_calc_fu_361_ap_start_reg;

assign i_fu_1123_p2 = (i_op_assign_reg_326 + 12'd1);

assign index_2_fu_1151_p2 = (24'd1 + index_1_reg_316);

assign index_3_fu_609_p2 = (tmp_2_cast_reg_1325 + index_reg_293);

assign indvars_iv_next_fu_1283_p2 = (tmp_2_cast_reg_1325 + indvars_iv_reg_262);

assign lhs_V_3_fu_1200_p1 = $signed(p_Val2_28_reg_272);

assign lhs_V_7_cast_fu_467_p1 = width_V_read_reg_1288;

assign lhs_V_8_cast_fu_500_p1 = X0_V_read_reg_1301;

assign lhs_V_fu_369_p1 = $signed(X1_V);

assign line_V_fu_512_p2 = (t_V_1_reg_282 + 12'd1);

assign newIndex1_fu_1143_p1 = newIndex_fu_1133_p4;

assign newIndex3_fu_1110_p1 = newIndex2_reg_1375;

assign newIndex_fu_1133_p4 = {{i_op_assign_reg_326[11:2]}};

assign newsignbit_i_i_i_i_0_1_fu_796_p2 = (tmp_73_fu_754_p3 ^ 1'd1);

assign newsignbit_i_i_i_i_0_2_fu_920_p2 = (tmp_76_fu_878_p3 ^ 1'd1);

assign newsignbit_i_i_i_i_0_3_fu_1044_p2 = (tmp_79_fu_1002_p3 ^ 1'd1);

assign newsignbit_i_i_i_i_fu_672_p2 = (tmp_70_fu_630_p3 ^ 1'd1);

assign overflow_6_1_fu_790_p2 = (tmp_77_1_fu_784_p2 & brmerge28_1_fu_778_p2);

assign overflow_6_2_fu_914_p2 = (tmp_77_2_fu_908_p2 & brmerge28_2_fu_902_p2);

assign overflow_6_3_fu_1038_p2 = (tmp_77_3_fu_1032_p2 & brmerge28_3_fu_1026_p2);

assign overflow_6_fu_666_p2 = (tmp_32_fu_660_p2 & brmerge2_fu_654_p2);

assign p_0285_2_fu_1275_p3 = ((brmerge7_fu_1253_p2[0:0] === 1'b1) ? p_mux7_fu_1259_p3 : p_2_fu_1267_p3);

assign p_0_1_fu_854_p3 = ((brmerge31_1_fu_832_p2[0:0] === 1'b1) ? p_mux6_1_fu_838_p3 : p_9_1_fu_846_p3);

assign p_0_2_fu_978_p3 = ((brmerge31_2_fu_956_p2[0:0] === 1'b1) ? p_mux6_2_fu_962_p3 : p_9_2_fu_970_p3);

assign p_0_3_fu_1102_p3 = ((brmerge31_3_fu_1080_p2[0:0] === 1'b1) ? p_mux6_3_fu_1086_p3 : p_9_3_fu_1094_p3);

assign p_0_fu_730_p3 = ((brmerge5_fu_708_p2[0:0] === 1'b1) ? p_mux6_fu_714_p3 : p_9_fu_722_p3);

assign p_2_fu_1267_p3 = ((underflow_7_fu_1235_p2[0:0] === 1'b1) ? 40'd549755813888 : y_V_fu_1217_p1);

assign p_707_not_1_fu_826_p2 = (underflow_6_1_fu_814_p2 ^ 1'd1);

assign p_707_not_2_fu_950_p2 = (underflow_6_2_fu_938_p2 ^ 1'd1);

assign p_707_not_3_fu_1074_p2 = (underflow_6_3_fu_1062_p2 ^ 1'd1);

assign p_707_not_fu_702_p2 = (underflow_6_fu_690_p2 ^ 1'd1);

assign p_9_1_fu_846_p3 = ((underflow_6_1_fu_814_p2[0:0] === 1'b1) ? 40'd549755813888 : p_Val2_8_1_fu_750_p2);

assign p_9_2_fu_970_p3 = ((underflow_6_2_fu_938_p2[0:0] === 1'b1) ? 40'd549755813888 : p_Val2_8_2_fu_874_p2);

assign p_9_3_fu_1094_p3 = ((underflow_6_3_fu_1062_p2[0:0] === 1'b1) ? 40'd549755813888 : p_Val2_8_3_fu_998_p2);

assign p_9_fu_722_p3 = ((underflow_6_fu_690_p2[0:0] === 1'b1) ? 40'd549755813888 : p_Val2_8_fu_626_p2);

assign p_Result_20_fu_405_p3 = grp_fu_387_p2[32'd39];

assign p_Result_21_fu_1209_p3 = ret_V_14_fu_1204_p2[32'd40];

assign p_Result_22_fu_1221_p3 = ret_V_14_fu_1204_p2[32'd39];

assign p_Result_s_fu_393_p3 = grp_fu_387_p2[32'd40];

assign p_Val2_27_fu_401_p1 = grp_fu_387_p2[39:0];

assign p_Val2_8_1_fu_750_p2 = ($signed(X0_V_read_reg_1301) + $signed(tmp_71_reg_1385));

assign p_Val2_8_2_fu_874_p2 = ($signed(X0_V_read_reg_1301) + $signed(tmp_74_reg_1395));

assign p_Val2_8_3_fu_998_p2 = ($signed(X0_V_read_reg_1301) + $signed(tmp_77_reg_1405));

assign p_Val2_8_fu_626_p2 = ($signed(X0_V_read_reg_1301) + $signed(tmp_68_reg_1370));

assign p_mux6_1_fu_838_p3 = ((brmerge30_1_fu_820_p2[0:0] === 1'b1) ? 40'd549755813887 : p_Val2_8_1_fu_750_p2);

assign p_mux6_2_fu_962_p3 = ((brmerge30_2_fu_944_p2[0:0] === 1'b1) ? 40'd549755813887 : p_Val2_8_2_fu_874_p2);

assign p_mux6_3_fu_1086_p3 = ((brmerge30_3_fu_1068_p2[0:0] === 1'b1) ? 40'd549755813887 : p_Val2_8_3_fu_998_p2);

assign p_mux6_fu_714_p3 = ((brmerge4_fu_696_p2[0:0] === 1'b1) ? 40'd549755813887 : p_Val2_8_fu_626_p2);

assign p_mux7_fu_1259_p3 = ((brmerge6_fu_1241_p2[0:0] === 1'b1) ? 40'd549755813887 : y_V_fu_1217_p1);

assign p_mux_fu_443_p3 = ((brmerge_fu_425_p2[0:0] === 1'b1) ? 40'd549755813887 : p_Val2_27_fu_401_p1);

assign p_not2_1_fu_802_p2 = ((tmp_19_fu_762_p4 != 12'd4095) ? 1'b1 : 1'b0);

assign p_not2_2_fu_926_p2 = ((tmp_20_fu_886_p4 != 12'd4095) ? 1'b1 : 1'b0);

assign p_not2_3_fu_1050_p2 = ((tmp_21_fu_1010_p4 != 12'd4095) ? 1'b1 : 1'b0);

assign p_not2_fu_678_p2 = ((tmp_18_fu_638_p4 != 12'd4095) ? 1'b1 : 1'b0);

assign p_not_1_fu_772_p2 = ((tmp_19_fu_762_p4 != 12'd0) ? 1'b1 : 1'b0);

assign p_not_2_fu_896_p2 = ((tmp_20_fu_886_p4 != 12'd0) ? 1'b1 : 1'b0);

assign p_not_3_fu_1020_p2 = ((tmp_21_fu_1010_p4 != 12'd0) ? 1'b1 : 1'b0);

assign p_not_fu_648_p2 = ((tmp_18_fu_638_p4 != 12'd0) ? 1'b1 : 1'b0);

assign p_s_fu_451_p3 = ((underflow_fu_419_p2[0:0] === 1'b1) ? 40'd549755813888 : p_Val2_27_fu_401_p1);

assign p_shl_fu_470_p3 = {{width_V_read_reg_1288}, {2'd0}};

assign pix_x_V_1_fu_565_p2 = (tmp_V_1_reg_305 | 12'd2);

assign pix_x_V_2_fu_584_p2 = (tmp_V_1_reg_305 | 12'd3);

assign pix_x_V_3_fu_603_p2 = (12'd4 + tmp_V_1_reg_305);

assign pix_x_V_s_fu_546_p2 = (tmp_V_1_reg_305 | 12'd1);

assign r_V_23_1_fu_556_p0 = r_V_23_1_fu_556_p00;

assign r_V_23_1_fu_556_p00 = pix_x_V_s_fu_546_p2;

assign r_V_23_1_fu_556_p1 = tmp_31_reg_1332;

assign r_V_23_1_fu_556_p2 = ($signed({{1'b0}, {r_V_23_1_fu_556_p0}}) * $signed(r_V_23_1_fu_556_p1));

assign r_V_23_2_fu_575_p0 = r_V_23_2_fu_575_p00;

assign r_V_23_2_fu_575_p00 = pix_x_V_1_fu_565_p2;

assign r_V_23_2_fu_575_p1 = tmp_31_reg_1332;

assign r_V_23_2_fu_575_p2 = ($signed({{1'b0}, {r_V_23_2_fu_575_p0}}) * $signed(r_V_23_2_fu_575_p1));

assign r_V_23_3_fu_594_p0 = r_V_23_3_fu_594_p00;

assign r_V_23_3_fu_594_p00 = pix_x_V_2_fu_584_p2;

assign r_V_23_3_fu_594_p1 = tmp_31_reg_1332;

assign r_V_23_3_fu_594_p2 = ($signed({{1'b0}, {r_V_23_3_fu_594_p0}}) * $signed(r_V_23_3_fu_594_p1));

assign r_V_s_fu_527_p0 = r_V_s_fu_527_p00;

assign r_V_s_fu_527_p00 = tmp_V_1_reg_305;

assign r_V_s_fu_527_p1 = tmp_31_reg_1332;

assign r_V_s_fu_527_p2 = ($signed({{1'b0}, {r_V_s_fu_527_p0}}) * $signed(r_V_s_fu_527_p1));

assign ret_V_14_fu_1204_p2 = ($signed(lhs_V_3_fu_1200_p1) - $signed(rhs_V_4_reg_1348));

assign ret_V_18_1_fu_738_p2 = ($signed(lhs_V_8_cast_reg_1340) + $signed(r_V_23_1_reg_1380));

assign ret_V_18_2_fu_862_p2 = ($signed(lhs_V_8_cast_reg_1340) + $signed(r_V_23_2_reg_1390));

assign ret_V_18_3_fu_986_p2 = ($signed(lhs_V_8_cast_reg_1340) + $signed(r_V_23_3_reg_1400));

assign ret_V_fu_477_p2 = (p_shl_fu_470_p3 - lhs_V_7_cast_fu_467_p1);

assign ret_V_s_fu_614_p2 = ($signed(lhs_V_8_cast_reg_1340) + $signed(r_V_s_reg_1365));

assign rhs_V_4_fu_503_p1 = delta_V_fu_459_p3;

assign rhs_V_fu_373_p0 = X0_V;

assign rhs_V_fu_373_p1 = rhs_V_fu_373_p0;

assign signbit_i_i_0_not_fu_1247_p2 = (p_Result_21_fu_1209_p3 ^ 1'd1);

assign signbit_i_i_i_i27_0_s_fu_431_p2 = (p_Result_s_fu_393_p3 ^ 1'd1);

assign tmp_18_fu_638_p4 = {{ret_V_s_fu_614_p2[51:40]}};

assign tmp_19_fu_762_p4 = {{ret_V_18_1_fu_738_p2[51:40]}};

assign tmp_20_fu_886_p4 = {{ret_V_18_2_fu_862_p2[51:40]}};

assign tmp_21_fu_1010_p4 = {{ret_V_18_3_fu_986_p2[51:40]}};

assign tmp_22_fu_1186_p1 = mem_0_q0;

assign tmp_22_fu_1186_p2 = mem_1_q0;

assign tmp_22_fu_1186_p3 = mem_2_q0;

assign tmp_22_fu_1186_p4 = mem_3_q0;

assign tmp_22_fu_1186_p5 = tmp_83_reg_1449;

assign tmp_2_cast_fu_493_p1 = width_V_read_reg_1288;

assign tmp_31_fu_496_p1 = delta_V_fu_459_p3;

assign tmp_32_fu_660_p2 = (tmp_69_fu_618_p3 ^ 1'd1);

assign tmp_34_fu_1229_p2 = (p_Result_22_fu_1221_p3 ^ 1'd1);

assign tmp_35_fu_1157_p1 = index_1_reg_316;

assign tmp_68_fu_532_p1 = r_V_s_fu_527_p2[39:0];

assign tmp_69_fu_618_p3 = ret_V_s_fu_614_p2[32'd51];

assign tmp_70_fu_630_p3 = p_Val2_8_fu_626_p2[32'd39];

assign tmp_71_fu_561_p1 = r_V_23_1_fu_556_p2[39:0];

assign tmp_72_fu_742_p3 = ret_V_18_1_fu_738_p2[32'd51];

assign tmp_73_fu_754_p3 = p_Val2_8_1_fu_750_p2[32'd39];

assign tmp_74_fu_580_p1 = r_V_23_2_fu_575_p2[39:0];

assign tmp_75_fu_866_p3 = ret_V_18_2_fu_862_p2[32'd51];

assign tmp_76_fu_878_p3 = p_Val2_8_2_fu_874_p2[32'd39];

assign tmp_77_1_fu_784_p2 = (tmp_72_fu_742_p3 ^ 1'd1);

assign tmp_77_2_fu_908_p2 = (tmp_75_fu_866_p3 ^ 1'd1);

assign tmp_77_3_fu_1032_p2 = (tmp_78_fu_990_p3 ^ 1'd1);

assign tmp_77_fu_599_p1 = r_V_23_3_fu_594_p2[39:0];

assign tmp_78_fu_990_p3 = ret_V_18_3_fu_986_p2[32'd51];

assign tmp_79_fu_1002_p3 = p_Val2_8_3_fu_998_p2[32'd39];

assign tmp_83_fu_1129_p1 = i_op_assign_reg_326[1:0];

assign tmp_s_fu_413_p2 = (p_Result_20_fu_405_p3 ^ 1'd1);

assign underflow_6_1_fu_814_p2 = (tmp_72_fu_742_p3 & brmerge29_1_fu_808_p2);

assign underflow_6_2_fu_938_p2 = (tmp_75_fu_866_p3 & brmerge29_2_fu_932_p2);

assign underflow_6_3_fu_1062_p2 = (tmp_78_fu_990_p3 & brmerge29_3_fu_1056_p2);

assign underflow_6_fu_690_p2 = (tmp_69_fu_618_p3 & brmerge3_fu_684_p2);

assign underflow_7_fu_1235_p2 = (tmp_34_fu_1229_p2 & p_Result_21_fu_1209_p3);

assign underflow_fu_419_p2 = (tmp_s_fu_413_p2 & p_Result_s_fu_393_p3);

assign y_V_fu_1217_p1 = ret_V_14_fu_1204_p2[39:0];

always @ (posedge ap_clk) begin
    tmp_2_cast_reg_1325[23:12] <= 12'b000000000000;
    buf_addr_reg_1479[31:24] <= 8'b00000000;
end

endmodule //calc
